@startuml
autonumber

Admin -> Backend: Kontroluje aukcje

Admin -> Backend: Usuwa aukcje
Backend -> BazaDanych: Usuwa wpis w bazie danych
BazaDanych --> Backend: Potwierdza usunięcie
Backend --> Admin: Informacja o usunięcie aukcji
Backend -> Wystawca: Informacja o usunięciu aukcji

@enduml